### ISSUE TITLE
xtra docs

### ISSUE THREAD

**Issue by peach-inzn** [googlefonts/amstelvar#219]
Hey, I know opening an issue certainly isn't the best way to ask this but how does xtra vary from width? Do you know any good documentation about x transparent?

**Comment by kenmcd** [comment]
xtra - https://variationsguide.typenetwork.com/#xtra 

It appears to me that xtra is a variation of the width of the interior white space.
Notice in the demo on the page above how the vertical strokes on the H stay the same.
Contrast that with width where everything changes.

**Comment by dberlow** [comment]
That is correct. A typical width axis varies the weight slightly, the spacing considerably and the widths of all the letters, inside and outside.

The XTRA axis leaves weight, spacing and parts external to glyphs alone and just varies the counter. This allows tiny changes, unnoticed by the reader, for use overall in the glyphs for justification, or for use on Individual letters for logo customization. 

On Feb 28, 2022, at 7:16 PM, kenmcd ***@***.***> wrote:

﻿
xtra - https://variationsguide.typenetwork.com/#xtra

It appears to me that xtra is a variation of the width of the interior white space.
Notice in the demo on the page above how the vertical strokes on the H stay the same.
Contrast that with width where everything changes.

**Comment by kenmcd** [comment]
Thanks for the clarification!

**Comment by dberlow** [comment]
There is a demo of this axis, and others in use, for fitting paragraphs and headlines in columns, here; https://graphicore.github.io/varla-varfo/explorations/wikipedia/Typography/firefox_save_page_as/Typography%20-%20Wikipedia.html

A menu is available to control the display, adjustments and etc in the upper left-hand corner of your browser. 

Right now, it’s functioning can eat your processor, but it will warn you.

On Mar 1, 2022, at 3:10 PM, kenmcd ***@***.***> wrote:

﻿
Thanks for the clarification!

**Comment by kenmcd** [comment]
> There is a demo of this axis, and others in use, for fitting paragraphs and headlines in columns, here; https://graphicore.github.io/varla-varfo/explorations/wikipedia/Typography/firefox_save_page_as/Typography%20-%20Wikipedia.html A menu is available to control the display, adjustments and etc in the upper left-hand corner of your browser. Right now, it’s functioning can eat your processor, but it will warn you.

Well, that's kinda fun. Thanks.
Is there a legend for the color coding available?

Have to play with that more later (or I will get nothing done today).
Think I will use some smaller pages and make some before-and-after images.
Good to have examples of the axis in use.

**Comment by peach-inzn** [comment]
@kenmcd @dberlow Thanks so much for both of your replies! This has been very insightful and helpful – much appreciated!
